### ISSUE TITLE
How to check which images belong to train/val set?

### ISSUE THREAD

**Issue by andreqwert** [aman5319/Multi-Label#2]
According to notebook random splitting is the following:
`trainset, valset = random_split(dataset, [len(dataset)-valid_no, valid_no])`
How to check which image paths are belong to trainset or valset?

**Comment by aman5319** [comment]
It's pretty simple
For valset
`dataset.df.loc[valset.indices]`

For trainset
`dataset.df.loc[trainset.indices]`

**Comment by andreqwert** [comment]
> It's pretty simple
> For valset
> `dataset.df.loc[valset.indices]`
> 
> For trainset
> `dataset.df.loc[trainset.indices]`


Passing list-likes to `.loc` is no longer supported but `trainset.indices` without `loc` resolved the issue. With these indices we can get the numbers of corresponding rows indeed. We can justapose it with initial dataframe and paths column in it.
Thanks a lot!

**Comment by aman5319** [comment]
Cool, you figured it out your way, But I tried the code on colab with loc it is working correctly, maybe some pandas version issue from your side.
Anyway, I will close the issue.

**Comment by andreqwert** [comment]
To check out what the images are belong to train/val set you can use:
```
for train_index in trainset.indices:
    print(df['image'].iloc[train_index])

for val_index in valset.indices:
    print(df['image'].iloc[val_index])
```
